### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by Seanman236** [munawirrahman/ScreenFlowPlatformEvent#1]
Thank you so much for putting this out there - very awesome!

I was wondering if you could provide some guidance for how to enhance this to control flow navigation rather than launch the flow as a modal?  

I am struggling with getting the lwc wired up to control the flows next/finish navigation and was worried it may just not be possible?

Thanks again for providing this and appreciate any help you may be able to offer :).

**Comment by munawirrahman** [comment]
hi,
thank you, its my pleasure.
I wonder do you need it as lwc? if you're ok doing it with aura, i think you can use [this resource](https://unofficialsf.com/from-gerald-enabling-flow-screens-to-respond-to-platform-events/) where you can do basically the same thing.

**Comment by Seanman236** [comment]
Hey there!  Wow thank you for sending that over!  Unfortunately…In this case we do need it as a lwc because we are using an LWR Experience/community which cannot use aura components.  Do you know how one would go about converting what you sent over to lwc? (Is that technically possible?)Thank you!! SeanOn Nov 22, 2022, at 7:03 AM, munawirrahman ***@***.***> wrote:﻿
hi,
thank you, its my pleasure.
I wonder do you need it as lwc? if you're ok doing it with aura, i think you can use this resource where you can do basically the same thing.

**Comment by munawirrahman** [comment]
Ah i see, i dont think there's a way to convert it to lwc. Based on your specification, it should be possible to do the same thing with lwc. We just need to put a platform event listener on the js and trigger navigation in case an event received. I may be able to take a look at it this weekend, will let you know how it goes

**Comment by munawirrahman** [comment]
Hi sorry im late a week for this.
I created a writing based on my understanding about your problem https://munawirrahman.medium.com/auto-navigate-screen-flow-with-platform-event-salesforce-c4ac943e416e
hope that solves your issue.

thanks

**Comment by Seanman236** [comment]
Wow! Truly thank you so much!SeanOn Dec 2, 2022, at 4:53 AM, munawirrahman ***@***.***> wrote:﻿
Closed #1 as completed.

**Comment by Seanman236** [comment]
Hey there!I hope this finds you well - I can’t thank you enough for the work you put in to this lwc component.  The navigation is working perfectly! Since we cannot declaratively query a prior platform event (and we have limits to our custom object availability) I’ve been trying to determine if and how I could add the ability to pass a string value with the platform event.  Was this component designed in such a way to be enhanced for this use case? If so do you have any suggestions or thoughts on how to accomplish this? I’m more than happy to try and tackle this for myself and report back - I’m just stumped on how to proceed. Thanks again for your time and all the best,SeanOn Dec 2, 2022, at 4:53 AM, munawirrahman ***@***.***> wrote:﻿
Hi sorry im late a week for this.
I created a writing based on my understanding about your problem https://munawirrahman.medium.com/auto-navigate-screen-flow-with-platform-event-salesforce-c4ac943e416e
hope that solves your issue.
thanks
